<?xml version="1.0" encoding="UTF-8"?>
<!--
Nombre: David Ruiz
Curso: Daw 1
Fecha: 02/04/2025
Ejercicio 3
-->
<!--Aeropuerto.-->
<!DOCTYPE panel [
    <!ELEMENT panel (aeropuerto, vuelos)>
    <!ATTLIST panel fecha CDATA #REQUIRED>
    <!ELEMENT aeropuerto (#PCDATA)>    
    <!ELEMENT vuelos (vuelo+)>
    <!ELEMENT vuelo (diario?, origen, destino, hora_salida, hora_llegada)>
    <!ATTLIST vuelo codigo ID #REQUIRED estado (C | E | R) "E">
    <!ELEMENT diario EMPTY>
    <!ELEMENT origen (#PCDATA)>
    <!ELEMENT destino (#PCDATA)>
    <!ELEMENT hora_salida (#PCDATA)>
    <!ELEMENT hora_llegada (#PCDATA)>
]>
<panel fecha="20/12/2013">
    <aeropuerto>JFK</aeropuerto>
    <vuelos>
        <vuelo codigo="V22" estado="R">
            <diario/>
            <origen>New York</origen>
            <destino>Chicago</destino>
            <hora_salida>9:30</hora_salida>
            <hora_llegada>11:30</hora_llegada>
        </vuelo>
        <vuelo codigo="V23" estado="C">
            <origen>New York</origen>
            <destino>Miami</destino>
            <hora_salida>10:15</hora_salida>
            <hora_llegada>11:15</hora_llegada>
        </vuelo>
    </vuelos>
</panel>
